# Generated by Django 5.2.8 on 2025-11-08 13:30

from django.db import migrations, models

import apps.users.models
import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображения вашего профиля', null=True, upload_to=apps.users.models.user_directory_path, validators=[apps.users.validators.validate_image_format]),
        ),
    ]
