# Generated by Django 5.2.8 on 2025-11-12 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('7a28bc15-4d82-4abe-92ba-4f052aaaac04'), unique=True),
        ),
    ]
