# Generated by Django 5.2.8 on 2025-11-13 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_passwordresettoken_code_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('34c22659-ed20-40ea-a205-d1f4a81e2b06'), unique=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
