# Generated by Django 5.2.8 on 2025-11-15 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usermessage_is_read_alter_passwordresettoken_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('05837629-488c-476c-86f3-968625a36aa4'), unique=True),
        ),
    ]
