# Generated by Django 5.2.8 on 2025-11-15 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_passwordresettoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('826ad163-8912-4772-ba19-61f9211d44b1'), unique=True),
        ),
    ]
