# Generated by Django 5.2.8 on 2025-11-15 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_passwordresettoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('6e468e11-789e-4965-b08e-e8ba2262dfb2'), unique=True),
        ),
    ]
