# Generated by Django 5.2.8 on 2025-11-16 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_passwordresettoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='code',
            field=models.UUIDField(default=uuid.UUID('eb8908ce-b515-488d-bb90-1baa1068b24d'), unique=True),
        ),
    ]
