# Generated by Django 5.2.8 on 2025-11-15 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('main', '0005_events_max_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(help_text='Выберите мероприятие', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.events'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event')},
        ),
    ]
