# Generated by Django 5.2.8 on 2025-11-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='events',
            name='date_of_events',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 12, 11, 46, 936108, tzinfo=datetime.timezone.utc), help_text='Дата начала мероприятия'),
            preserve_default=False,
        ),
    ]
