# Generated by Django 5.2.8 on 2025-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_events_options_events_date_of_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.CharField(default='', help_text='Длительность', max_length=9),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_events',
            field=models.DateTimeField(help_text='Дата проведения'),
        ),
    ]
