# Generated by Django 5.2.8 on 2025-11-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events_duration_events_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(default='', help_text='Место проведения', max_length=250),
        ),
    ]
