# Generated by Django 5.2.8 on 2025-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
