# Generated by Django 5.2.8 on 2025-11-16 09:59

from django.db import migrations, models

import apps.main.models
import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events_max_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Выберите изображения вашего профиля', null=True, upload_to=apps.main.models.event_directory_path, validators=[apps.users.validators.validate_image_format]),
        ),
    ]
